--------------------------------------------------------
--  File created - Wednesday-September-20-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MOVIE_CATEGORIES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MOVIE_CATEGORIES" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"URL" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MOVIES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MOVIES" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MOVIE_MOVIE_CATEGORY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MOVIE_MOVIE_CATEGORY" 
   (	"MOVIE_ID" NUMBER, 
	"MOVIE_CATEGORY_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GAMES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GAMES" 
   (	"ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(255 BYTE), 
	"URL" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOCATIONS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."LOCATIONS" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"X" FLOAT(126), 
	"Y" FLOAT(126), 
	"Z" FLOAT(126), 
	"IS_NAMED" NUMBER, 
	"GAME_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.MOVIE_CATEGORIES
SET DEFINE OFF;
Insert into SYSTEM.MOVIE_CATEGORIES (ID,NAME,URL) values (1,'Test Category','test');
REM INSERTING into SYSTEM.MOVIES
SET DEFINE OFF;
Insert into SYSTEM.MOVIES (ID,TITLE) values (64,'test1');
Insert into SYSTEM.MOVIES (ID,TITLE) values (65,'test2');
Insert into SYSTEM.MOVIES (ID,TITLE) values (66,'test3');
Insert into SYSTEM.MOVIES (ID,TITLE) values (67,'test4');
Insert into SYSTEM.MOVIES (ID,TITLE) values (68,'test5');
REM INSERTING into SYSTEM.MOVIE_MOVIE_CATEGORY
SET DEFINE OFF;
Insert into SYSTEM.MOVIE_MOVIE_CATEGORY (MOVIE_ID,MOVIE_CATEGORY_ID) values (64,1);
Insert into SYSTEM.MOVIE_MOVIE_CATEGORY (MOVIE_ID,MOVIE_CATEGORY_ID) values (65,1);
Insert into SYSTEM.MOVIE_MOVIE_CATEGORY (MOVIE_ID,MOVIE_CATEGORY_ID) values (66,1);
Insert into SYSTEM.MOVIE_MOVIE_CATEGORY (MOVIE_ID,MOVIE_CATEGORY_ID) values (67,1);
Insert into SYSTEM.MOVIE_MOVIE_CATEGORY (MOVIE_ID,MOVIE_CATEGORY_ID) values (68,1);
REM INSERTING into SYSTEM.GAMES
SET DEFINE OFF;
Insert into SYSTEM.GAMES (ID,TITLE,URL) values (1,'Call of Duty: Warzone 2.0 - Vondel','warzonetwo');
Insert into SYSTEM.GAMES (ID,TITLE,URL) values (2,'Fortnite','fortnite');
REM INSERTING into SYSTEM.LOCATIONS
SET DEFINE OFF;
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (2,'University',null,null,null,1,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (3,'City Hall',null,null,null,1,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (4,'Graveyard',null,null,null,1,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (5,'Mall',null,null,null,1,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (6,'Central Station',null,null,null,1,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (7,'Market',null,null,null,1,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (8,'Police Station',null,null,null,1,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (9,'Fire Department',null,null,null,1,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (10,'Museum',null,null,null,1,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (11,'Exhibt',null,null,null,1,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (12,'Floating District',null,null,null,1,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (13,'Zoo',null,null,null,1,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (14,'Stadium',null,null,null,1,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (15,'Cruise Terminal',null,null,null,1,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (16,'Souvenirs District',null,null,null,0,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (17,'Courtyard',null,null,null,0,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (1,'Castle',null,null,null,1,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (18,'Kuvstenaar District',null,null,null,0,1);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (512,'Sunswoon Lagoon',23472,-40824,1412,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (513,'ECLIPSED ESTATE',42704.00000000003,-73143.99999999999,1964,1,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (514,'Crude Harbor',116052,22236,3204,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (515,'Sandy Circle',-101624,-20752,1776,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (516,'Timbercut Camp',-52688,-13160,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (517,'Cedar Circle',-36068,79996,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (518,'CREEKY COMPOUND',27096,-15528,1964,1,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (439,'Kapok Cove',43512,-19416,1412,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (440,'Seaside Sentry',-16700,-110452,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (441,'MEGA CITY',-51724,27208,1964,1,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (442,'Eastern Watch',56580,-59828,2804,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (443,'Beached Bit',7720,80180,-1376,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (444,'SHATTERED SLABS',-17556,-83340,1964,1,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (445,'Whispering Waters',-83304,-20344,1776,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (446,'Frostbite Falls',49416,34884,2804,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (447,'Coastal Battlement',112076,-71460,2804,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (448,'Hidden Ruin',47112,-32252,860,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (449,'Shore Shack',-52812,-96308,2940,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (450,'Gusty Gorge',44752,25616,1964,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (451,'Icy Islets',52780,-3000,2804,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (452,'SLAPPY SHORES',19468,62984,-12,1,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (453,'The Hall of Whispers',29252,18428,3496,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (454,'Berg Barge',118500,-19536,688,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (455,'Bamboo Circle',-20396,12764,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (456,'Marine Monoliths',-86900,78232,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (457,'Western Watch',38116,-88856,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (458,'The Stone Tower',94060,10700,4484,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (459,'Fallow Fuel',-84328,59328,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (460,'Secluded Spire',3836,33568,-192,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (461,'Hidden Ruin',49996,-32252,972,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (462,'Trickchaser''s Jump',-45460,7160,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (463,'Moment''s Rest',-75904,65056,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (464,'Mesa''s Reach',-26392,45920,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (465,'Northern Ruin',101424,-9716,3064,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (466,'Restful Retreat',-21648,93180,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (467,'Hidden Ruin',44364,-32256,916,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (468,'Drift Ridge',-16348,31428,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (469,'Woodsy Ward',93132,-58576,2804,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (470,'Windcatch Lake',-51068,62216,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (471,'King''s Launch',65404,-105484,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (472,'The Getaway',-49224,-37800,0,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (473,'SHADY STILTS',83384,-21256,1964,1,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (474,'Sakura Circle',-119404,38092,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (475,'Neon Bay Bridge',-101684,16908,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (476,'Southern Ruin',-19020,-8752,1412,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (477,'Lotus Lookout',-108252,-12104,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (478,'Stormy Spire',79448,37312,12696,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (479,'Fireglow Sanctuary',-28728,64472,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (480,'Baywatcher Barge',-80148,38716,368,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (481,'RUMBLE RUINS',115.99999999995634,-44000.00000000002,1964,1,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (482,'SANGUINE SUITES',93375.40941955995,69472.31029668618,2803.9999999999563,1,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (483,'Forest Forge',2708,-96692,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (484,'Wildwind Sanctuary',-35672,-244,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (485,'Slap N'' Gone',5140,19948,-192,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (486,'Twilight Torch',-50604,99944,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (487,'Rowdy Acres',-70576,-36704,2940,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (488,'Hitches and Ditches',-22664,-21184,768,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (489,'Burning Beacon',-120912,20676,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (490,'Mayday Landing',76896,-41984.00000000003,3064,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (491,'Luminous Lantern',-106544,9140,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (492,'BREAKWATER BAY',87688,-88244,2804,1,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (493,'Placid Pond',-41000,-15292,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (494,'BRUTAL BASTION',61856,32312,1964,1,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (495,'Mogul Home',35328,27792,2804,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (496,'Aegis Temple',97216,43752,3204,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (497,'Beep ''n Bounce',112280,6372,4484,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (498,'Windrush Ravine',-38224,-10512,56,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (499,'Feudal Fuel',71228,-49828,2804,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (500,'Frosty Firs',92292,5948,1964,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (501,'STEAMY SPRINGS',-85748,-5756,1964,1,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (502,'Rocky Docks',-26004,-111480,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (503,'FRENZY FIELDS',-52584,-33532,1964,1,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (504,'KENJUTSU CROSSING',-101504,55384,1964,1,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (505,'Crackshot''s Cabin',40352,936,3836,1,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (506,'RELENTLESS RETREAT',-70104,-78080,2944,1,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (507,'KNOTTY NETS',-62772,93844,1964,1,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (508,'The Apparatus',-204,-560,1412,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (509,'Coldwater Sanctuary',-82644,25392,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (510,'Royal Ruin',39536,-113980,1992,0,2);
Insert into SYSTEM.LOCATIONS (ID,NAME,X,Y,Z,IS_NAMED,GAME_ID) values (511,'Crusty Crates',52356,80792,1108,0,2);
--------------------------------------------------------
--  DDL for Index SYS_C008338
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008338" ON "SYSTEM"."MOVIE_CATEGORIES" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008339
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008339" ON "SYSTEM"."MOVIE_CATEGORIES" ("URL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MOVIE_CATEGORIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."MOVIE_CATEGORIES_PK" ON "SYSTEM"."MOVIE_CATEGORIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008334
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008334" ON "SYSTEM"."MOVIES" ("TITLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MOVIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."MOVIES_PK" ON "SYSTEM"."MOVIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MOVIE_MOVIE_CATEGORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_MOVIE_MOVIE_CATEGORY" ON "SYSTEM"."MOVIE_MOVIE_CATEGORY" ("MOVIE_ID", "MOVIE_CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008315
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008315" ON "SYSTEM"."GAMES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008320
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008320" ON "SYSTEM"."LOCATIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger MOVIE_CATEGORIES_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."MOVIE_CATEGORIES_TRIGGER" 
BEFORE INSERT ON movie_categories
FOR EACH ROW
BEGIN
    SELECT movie_categories_autoincrement.NEXTVAL
    INTO :NEW.id
    FROM dual;
END;
/
ALTER TRIGGER "SYSTEM"."MOVIE_CATEGORIES_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MOVIES_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."MOVIES_TRIGGER" 
BEFORE INSERT ON movies
FOR EACH ROW
BEGIN
   SELECT movies_autoincrement.NEXTVAL
   INTO :NEW.id
   FROM dual;
END;
/
ALTER TRIGGER "SYSTEM"."MOVIES_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger GAMES_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."GAMES_TRIGGER" 
BEFORE INSERT ON games
FOR EACH ROW
BEGIN
    SELECT games_autoincrement.NEXTVAL
    INTO :NEW.id
    FROM dual;
END;

/
ALTER TRIGGER "SYSTEM"."GAMES_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOCATIONS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."LOCATIONS_TRIGGER" 
BEFORE INSERT ON locations
FOR EACH ROW
BEGIN
    SELECT locations_autoincrement.NEXTVAL
    INTO :NEW.id
    FROM dual;
END;

/
ALTER TRIGGER "SYSTEM"."LOCATIONS_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table MOVIE_CATEGORIES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MOVIE_CATEGORIES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MOVIE_CATEGORIES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MOVIE_CATEGORIES" MODIFY ("URL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MOVIE_CATEGORIES" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."MOVIE_CATEGORIES" ADD UNIQUE ("URL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."MOVIE_CATEGORIES" ADD CONSTRAINT "MOVIE_CATEGORIES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MOVIES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MOVIES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MOVIES" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MOVIES" ADD UNIQUE ("TITLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."MOVIES" ADD CONSTRAINT "MOVIES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MOVIE_MOVIE_CATEGORY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MOVIE_MOVIE_CATEGORY" MODIFY ("MOVIE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MOVIE_MOVIE_CATEGORY" MODIFY ("MOVIE_CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MOVIE_MOVIE_CATEGORY" ADD CONSTRAINT "PK_MOVIE_MOVIE_CATEGORY" PRIMARY KEY ("MOVIE_ID", "MOVIE_CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GAMES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GAMES" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GAMES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GAMES" MODIFY ("URL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCATIONS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LOCATIONS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOCATIONS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."LOCATIONS" MODIFY ("IS_NAMED" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOCATIONS" MODIFY ("GAME_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MOVIE_MOVIE_CATEGORY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MOVIE_MOVIE_CATEGORY" ADD CONSTRAINT "FK_MOVIE" FOREIGN KEY ("MOVIE_ID")
	  REFERENCES "SYSTEM"."MOVIES" ("ID") ENABLE;
  ALTER TABLE "SYSTEM"."MOVIE_MOVIE_CATEGORY" ADD CONSTRAINT "FK_MOVIE_CATEGORY" FOREIGN KEY ("MOVIE_CATEGORY_ID")
	  REFERENCES "SYSTEM"."MOVIE_CATEGORIES" ("ID") ENABLE;
